# Generated by Django 4.1.2 on 2022-10-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Famille",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="animal",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="info.famille"
            ),
        ),
    ]
