# Generated by Django 4.1.3 on 2022-11-28 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='jaime',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 14, 10, 19, 135801)),
        ),
    ]
