# Generated by Django 4.1.3 on 2022-11-28 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_gif_jaime_alter_gif_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='jaime',
        ),
        migrations.AddField(
            model_name='gif',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 14, 15, 25, 979332)),
        ),
    ]
