# Generated by Django 4.1.4 on 2022-12-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecoges", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="dateCreation",),
    ]
