# Generated by Django 4.1.4 on 2022-12-29 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecoges", "0002_remove_user_datecreation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=70)),
                ("dateNaissance", models.DateField()),
                ("lieuNaissance", models.CharField(max_length=90)),
                ("genre", models.CharField(max_length=10)),
                ("nationalite", models.CharField(max_length=20)),
                ("statut", models.CharField(max_length=90)),
                ("telephone", models.CharField(max_length=18)),
                ("adresse", models.CharField(max_length=40)),
                ("nomPrenomPAB", models.CharField(max_length=100)),
                ("contactPAB", models.CharField(max_length=18)),
                (
                    "idUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
