# Generated by Django 4.1.4 on 2023-01-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecoges", "0004_enseignantmatiere"),
    ]

    operations = [
        migrations.RemoveField(model_name="enseignantmatiere", name="anneeScolaire",),
    ]
