# Generated by Django 4.1.4 on 2023-01-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecoges", "0005_remove_enseignantmatiere_anneescolaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnseignantClasseMatiere",
            fields=[
                (
                    "idEnseignantClasseMatiere",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dateAttribution", models.DateTimeField()),
                ("supprimer", models.BooleanField(default=False)),
                ("dateSuppression", models.DateTimeField(null=True)),
                (
                    "anneeScolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecoges.anneescolaire",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecoges.classe"
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecoges.enseignant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecoges.matiere"
                    ),
                ),
            ],
        ),
    ]
