# Generated by Django 4.1.4 on 2023-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoges", "0006_enseignantclassematiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignantclassematiere",
            name="coefficient",
            field=models.IntegerField(default=1),
        ),
    ]
